multikernel: Depend on the memory APIs the core needs
The core allocates pool memory with alloc_contig_range() and hands it
to instances with add_memory_driver_managed() and
offline_and_remove_memory(). None of these has a fallback when its
option is off, so x86_64_defconfig plus CONFIG_MULTIKERNEL=y does not
build:

  kernel/multikernel/contig.c:31:22: error: implicit declaration of function 'alloc_contig_range'
  kernel/multikernel/hotplug.c:436:15: error: implicit declaration of function 'add_memory_driver_managed'
  kernel/multikernel/hotplug.c:450:17: error: implicit declaration of function 'offline_and_remove_memory'

Declare the contiguous-allocation and memory-hotplug dependencies so
CONFIG_MULTIKERNEL cannot expose an unbuildable configuration.

[Kconfig dependencies only, picked from the RISC-V skeleton in
 https://github.com/multikernel/linux/pull/37]

Signed-off-by: Nikolay Nikolaev <nicknickolaev@gmail.com>
Signed-off-by: Cong Wang <cwang@multikernel.io>