kexec: Fix the CONFIG_KEXEC_FILE=n build of /proc/kimage
struct kimage only has cmdline_buf when CONFIG_KEXEC_FILE is on, but
kexec_core.c reads it unconditionally to free it in kimage_free() and
to print it in /proc/kimage:

  kernel/kexec_core.c:689:28: error: 'struct kimage' has no member named 'cmdline_buf'

Move both accesses into kexec_file.c behind helpers with empty stubs
for the off case, the same way kimage_file_post_load_cleanup() is
handled. No change to the /proc/kimage output.

Signed-off-by: Cong Wang <cwang@multikernel.io>